apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db
  replicas: 3
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: michaelyi/db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        env:
          - name: SPDLOG_LEVEL
            value: debug,mylogger=trace
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  clusterIP: None
  selector:
    app: db
  ports:
  - port: 50051
    targetPort: 50051
