apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
spec:
  replicas: 3
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: michaelyi/router:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
        env:
          - name: SPDLOG_LEVEL
            value: debug,mylogger=trace
---
apiVersion: v1
kind: Service
metadata:
  name: router
spec:
  type: LoadBalancer
  selector:
    app: router 
  ports:
  - port: 80
    targetPort: 50051
