apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkvdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dkvdb
  template:
    metadata:
      labels:
        app: dkvdb 
    spec:
      containers:
      - name: dkvdb
        image: michaelyi/dkvdb:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
